import Header from "@/components/Layout/Header";
import Sidebar from "@/components/Layout/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <div className="main-layout">
      <Sidebar/>
      <div className="children">
        <Header/>
        {children}
      </div>
    </div>
  );
}
