import Sidebar from "@/components/Layout/Sidebar";
import {Box, Stack} from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <Stack sx={{flexDirection: "row"}}>
      <Sidebar/>
      <Box sx={{width: 'calc(100% - 250px)',p:2}}>
        {children}
      </Box>
    </Stack>
  );
}
